trigger:
- '*'

variables: 
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  WebAppName: 'tailspin-space-game-web-30593' 
  ResourceGroupName: 'tailspin-space-game-rg'
  ServiceConnection: 'Resource Manager - Tailspin - Space Game'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: 'Container Registry Connection'
        tags: |
          $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'
   
    
    steps:
    #- task: AzureWebAppContainer@1
    #  inputs:
    #   appName: $(WebAppName)
    #   azureSubscription: 'Resource Manager - Tailspin - Space Game'
    #   imageName: $(RegistryName)/$(webRepository):$(build.buildId)

    - task: AzureCLI@2
      displayName: 'Deploy to web app'
      inputs:
        azureSubscription: '$(ServiceConnection)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: az webapp config container set --name "$(WebAppName)" --resource-group "$(ResourceGroupName)" 