trigger:
- '*'

variables: 
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  webAppName: 'tailspin-space-game-web-30593' 
  resourceGroupName: 'tailspin-space-game-rg'
  azureSubscription: 'Azure subscription 1'
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'Container Registry Connection'
  containerRegistry: 'Resource Manager - Tailspin - Space Game'
  vmImageName: 'ubuntu-20.04'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: $(vmImageName)
    steps:   
    #- task: AzureCLI@2
    #  displayName: 'Deploy to web app'
    #  inputs:
    #    azureSubscription: $(ServiceConnection)
    #    scriptType: 'pscore'
    #    scriptLocation: 'inlineScript'
    #    inlineScript: 'az webapp config container set --name $(WebAppName) --resource-group $(ResourceGroupName)'
    - task: AzureWebAppContainer@1
      inputs:
        appName: $(webAppName)
        azureSubscription: $(azureSubscription)
        imageName: '$(containerRegistry)/$(webRepository):$(tag)'
        
        